[package]
name = "const_panic"
version = "0.0.0"
authors = ["rodrimati1992 <rodrimatt1985@gmail.com>"]
edition = "2021"
license = "Zlib"
description = "Basic const panic with Display-formatting, coming before Rust 1.57.0."

[dependencies]

[features]
default = ["all_items"]
all_items = []
