[package]
name = "const_panic"
version = "0.0.0"
authors = ["rodrimati1992 <rodrimatt1985@gmail.com>"]
edition = "2021"
license = "Zlib"
description = "Basic const panic with Display-formatting, coming before Rust 1.57.0."

[dependencies]

[dev-dependencies]
konst = "0.2.13"


[features]
default = ["non_basic"]
array_string = []
non_basic = ["array_string"]

# private feature
test = ["array_string"]
