name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 2
      matrix:
        rust: [stable, beta, nightly, 1.64.0, 1.57.0]

    steps:
    - uses: actions/checkout@v2
    - name: ci-1.64
      if: ${{ matrix.rust != '1.57.0' }}
      run: |
        rustup override set ${{ matrix.rust }}
        cargo update

        cd "${{github.workspace}}/"

        cargo test --no-default-features --features "test rust_1_64"
        cargo test --no-default-features --features "test __for_konst"

    - name: ci-all-versions
      run: |
        rustup override set ${{ matrix.rust }}
        cargo update
          
        cd "${{github.workspace}}/const_panic_proc_macros/"
        cargo test

        cd "${{github.workspace}}/"
        cargo build --no-default-features
        cargo build
        cargo test --features "test"
        cargo test --no-default-features --features "test "
        cargo test --no-default-features --features "test non_basic"
        cargo test --no-default-features --features "test non_basic derive"

